image: atlassian/default-image:4

definitions:
  services:
    4m-memory:
      memory: 3072
      type: docker
  steps:
    - step: &Build
        name: Build Image
        services: [4m-memory]
        script:
          - docker build -t registry.digitalklang.de/bsr/$IMAGE_NAME:$BITBUCKET_BUILD_NUMBER -t registry.digitalklang.de/bsr/$IMAGE_NAME:latest --build-arg STRAPI_URL=$STRAPI_URL --build-arg MATOMO_SITE_ID=$MATOMO_SITE_ID .
          - docker login -u $REGISTRY_USR -p $REGISTRY_PWD registry.digitalklang.de
          - docker push registry.digitalklang.de/bsr/$IMAGE_NAME --all-tags

pipelines:
  branches:        
    main:
      - step:
          <<: *Build
          deployment: Production
    develop:
      - step:
          <<: *Build
          deployment: Development