server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root /usr/share/nginx/html;  # Define the root outside location blocks

    location /assets/ {
      # Since root is already defined, this location will serve assets from /usr/share/nginx/html/assets
      access_log off;  # Optional: disables logging for this location
    }

    location / {
      try_files $uri $uri/ /index.html;  # Correctly redirect to index.html
    }
}