name: Build and deploy repami-frontend

on:
  push:
    branches:
      - deploy/dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/deploy/prod' && 'prod' || github.ref == 'refs/heads/deploy/dev' && 'dev' || 'dev'}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Log in to Azure Container Registry"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: "Build and push image"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}/repami-frontend:latest
          build-args: |
            STRAPI_URL=${{ secrets.STRAPI_URL }}
